name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake SVG
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Noumancoding
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake SVG to `output` branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan output
          git reset
          mv dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "ğŸ Generate Snake animation"
          git push -f origin output
